<a href="https://colab.research.google.com/github/Addair40/colab/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [5]:
import numpy as np

In [6]:
np.__version__

'1.21.6'

In [7]:
lista = [1,2,3,4,3]
array = np.array(lista)
#array.ndim       #NUMERO DE DIMENSIONES
#array.shape      #NUMERO DE DIMENSIONES QUE TIENE CADA APARTADO
#array.size       #CUANTOS ELEMENTOS TIENE EN TOTAL
#array.dtype      #TIPO DE DATO 
#array.itemsize   #NUMERO DE BITS QUE ESTA OCUPANDO PARA ALMACENAR ESOS VALORES
#array.data       #DA LA RUTA Y MEMORIA DONDE ESTA GUARDADO
#type(array)      #TIPO DE DATO
#array.max()      #VALOR MAXIMO
#array.min()      #VALOR MINIMO 

array([1, 2, 3, 4, 3])

In [ ]:
lista1 = [1,2,3]
lista2 = [4,5,6]
array = np.array([lista1,lista2])
#array.ndim       #NUMERO DE DIMENSIONES
#array.shape      #NUMERO DE DIMENSIONES QUE TIENE CADA APARTADO
#array.size       #CUANTOS ELEMENTOS TIENE EN TOTAL
#array.dtype      #TIPO DE DATO 
#array.itemsize   #NUMERO DE BITS QUE ESTA OCUPANDO PARA ALMACENAR ESOS VALORES
#array.data       #DA LA RUTA Y MEMORIA DONDE ESTA GUARDADO
#type(array)      #TIPO DE DATO
#array.max()      #VALOR MAXIMO
#array.min()      #VALOR MINIMO 

In [ ]:
lista1 = [1,2,3]
lista2 = [4,5,6]
lista3 = [6,7,8,9]
#array = np.array([lista1,lista2,lista3])
#array = np.array([lista1],dtype = int64)
#array = np.array([lista1],dtype = int32)
#array = np.array([lista1],dtype = float)
#array = np.array([lista1],dtype = int16)
#array
#array.ndim       #NUMERO DE DIMENSIONES
#array.shape      #NUMERO DE DIMENSIONES QUE TIENE CADA APARTADO
#array.size       #CUANTOS ELEMENTOS TIENE EN TOTAL
#array.dtype      #TIPO DE DATO 
#array.itemsize   #NUMERO DE BITS QUE ESTA OCUPANDO PARA ALMACENAR ESOS VALORES
#array.data       #DA LA RUTA Y MEMORIA DONDE ESTA GUARDADO
#type(array)      #TIPO DE DATO
#array.max()      #VALOR MAXIMO
#array.min()      #VALOR MINIMO 

In [11]:
array = np.arange(5) #ARANGE SIMULA COMO UN FOR
np.arange(5, 10 ,3)
array

array([0, 1, 2, 3, 4])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.linspace(0,9,4) #LINSPACE PERMITE GENERAR N NUMEROS ENTRE UN RANGO DE VALORES Y TODOS ESTARAN A LA MISMA DISTANCIA

array([0., 3., 6., 9.])