<a href="https://colab.research.google.com/github/Addair40/colab/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
from numpy import int32

In [2]:
array = np.array([1,2,3,3])
#array.argmax()         #INDICE DEL VALOR MAXIMO
#array.argmin()         #INDICE DEL VALOR MINIMO
#array.max()            #VALOR MAXIMO
#array.min()            #VALOR MINIMO

In [3]:
array = np.array([1,2,3,3])
array.astype(dtype = float)
array

array([1, 2, 3, 3])

In [4]:
array = array.astype(dtype = float)
array2 = array.copy()   #COPIA DE UN ARRAY
array2.fill(0)
array2
array.dump("datos.pk")  #CONVIERTE LOS DATOS EN BINARIO Y LOS ALMACENA 

In [5]:
x = np.load("datos.pk", allow_pickle=True)  #REGRESA LOS DATOS GUARDADOS
x

array([1., 2., 3., 3.])

In [6]:
array.dumps()

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x04\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00f8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X!\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc3\xb0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [9]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=int32)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [10]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=int32)
array = array.flatten()
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [11]:
array.item(4)  #DEVUELVE LA POSICION EN LA QUE SE ENCUENTRA

5

In [13]:
array = np.array([0,1,0,3,4,0],dtype=int32)  #MUESTRA LOS INDICES DONDE NO VIENEN LOS 0
array.nonzero()

(array([1, 3, 4]),)

In [ ]:
array = np.array([1,2,3],dtype=int32)  #MULTIPLICA LOS NUMEROS Y DEVULEVE TODOS LOS PRODUCTOS, SI TIENE 0 NO FUNCIONA
#array.prod()                          
#array.prod(initial = 3)      


In [16]:
from numpy import repeat


array = np.array([1,2,3],dtype=int32)
#array.repeat(repeats=3) 
array = array.repeat(repeats=3)
array.reshape(3,3)


array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]], dtype=int32)

In [17]:
array = np.array([1,2,3],dtype=int32)
#array.repeat(repeats=3) 
array = array.repeat(repeats=3)
array.reshape(1,9)


array([[1, 1, 1, 2, 2, 2, 3, 3, 3]], dtype=int32)

In [18]:
array = np.array([[1,2],[3,4]],dtype=int32)
array
np.resize(array,(4,3))

array([[1, 2, 3],
       [4, 1, 2],
       [3, 4, 1],
       [2, 3, 4]], dtype=int32)

In [19]:
array = np.array([[1,2,3],[4,1,2],[3,4,1],[2,3,4]],dtype=int32)
array.sort(axis = 1,kind = 'quicksort')    #axis = 0  ORDENA EN COLUMNAS
                                           #axis = 1  ORDENA EN FILAS
array

array([[1, 2, 3],
       [1, 2, 4],
       [1, 3, 4],
       [2, 3, 4]], dtype=int32)

In [20]:
from numpy import swapaxes


array = np.array([[0,1],[2,3]],dtype=int32)
array.swapaxes(1,0)             #0 - COLUMNAS
                                #1 - FILAS

array([[0, 2],
       [1, 3]], dtype=int32)

In [21]:
array = np.array([1,2,3,4,5],dtype=int32)
array.take([2,4])


array([3, 5], dtype=int32)